[[overview]]
= Spring 框架总览
:toc: left
:toclevels: 1
:docinfo1:

Spring框架使大型程序开发变得不再困难. 它提供了你进入java大型程序开发环境所需要的一切,同时有兼容支持JVM上的其它备选语言如Kotlin，Groovy, 能够灵活的适应各种程序需要的开发架构. Spring5 支持 JDK 8+ (Java SE 8+) 并且提供了对JDK9的默认支持。

Spring支持各种应用场景。 在大型企业, 程序开发运行周期通常都非常的长，JDK的版本也不是开发人员可以控制的。也有可能会以一个独立jar包内置服务器的形式存在。,
也有可能时云环境，也有可能是不需要服务器的独立应用程序 (例如批处理或者集成系统)

Spring 是开源的 它有一个巨大且活跃的社区来反馈，世界各地各种各样的不同用户在不同用例上提出的反馈. 这让spring成功的发展了很久。




[[overview-spring]]
== "Spring" 是什么意思

Spring这个术语在不同的语境中，有很多不同的意思. 你可以认为它是指Spring框架本身也就是Spring的出处, 随着时间的发展Spring产生了很多子项目。通常人们说起Spring就是指的Spring整个项目， 本文档主要面向Spring框架的基础，也就是Spring框架本身。

spring 被分为不同的模块，应用可以选择使用它们需要的模块。
核心部分是容器模块, 包括一个配置文件模型和一个依赖注入的机制. 除此之外spring也提供了基础的应用工程的支持, 包括 消息队列, 数据事务 and
持久化, 以及网络开发。 它也包含基于servlet的 Spring MVC 框架 以及Spring WebFlux reactive WEB框架（不需要servlet）.

关于modules的注意事项: Spring's framework 的jar包 允许使用JDK 9的 module路径
("Jigsaw"). 对于使用了Jigsaw的应用, Spring5 默认是有提供模块名的，这是独立于jar包名的，不受其影响的基于语言级别的模块名。
当然Spring框架的jar包可以在JDK9和jdk8的classpath里工作的很好。




[[overview-history]]
== Spring和Spring框架的历史

Spring始创于2003年，以应对早期
https://en.wikipedia.org/wiki/Java_Platform,_Enterprise_Edition[J2EE] 标准的复杂
有人认为Spring和J2EE是竞争对手, Spring确实是J2EE的竞争对手，实际上Spring并没有完全拥抱J2EE的标准，Spring只是选在了必要的精选的几个标准进行支持。

* Servlet API (https://jcp.org/en/jsr/detail?id=340[JSR 340])
* WebSocket API (https://www.jcp.org/en/jsr/detail?id=356[JSR 356])
* Concurrency Utilities (https://www.jcp.org/en/jsr/detail?id=236[JSR 236])
* JSON Binding API (https://jcp.org/en/jsr/detail?id=367[JSR 367])
* Bean Validation (https://jcp.org/en/jsr/detail?id=303[JSR 303])
* JPA (https://jcp.org/en/jsr/detail?id=338[JSR 338])
* JMS (https://jcp.org/en/jsr/detail?id=914[JSR 914])
* 也需要 JTA/JCA 以支持分布式事务，如果需要的话。

Spring也支持，依赖注入
(https://www.jcp.org/en/jsr/detail?id=330[JSR 330]) 和(https://jcp.org/en/jsr/detail?id=250[JSR 250])注释标准, 部分开发者可能不会选择使用Spring的依赖注入机制而采用这些标准

对于 Spring Framework 5.0而言，它需要至少java EE 7的支持(例如 Servlet 3.1+, JPA 2.1+)
默认支持java EE 8(例如Servlet 4.0, JSON Binding API)在不同的运行时都是兼容的例如Tomcat 8 , tomcat9  WebSphere 9以及JBoss EAP 7.

随着时间的发展javaEE开发也在发展. 早期的javaEE和Spring, 应用需要部署到应用服务器之中去。
现在随着springboot的发展, 应用变得更加devops-而且更加云友好， servlet容器被集成且变得不重要。
对于Spring甚至出现了不直接基于servlet的Spring web flux 它可以运行在非serlet容器之上例如netty。

Spring依然在创新发展,在Spring之上产生了很多项目，像如Spring Boot, Spring Security, Spring Data, Spring Cloud, Spring Batch, 参考 https://spring.io/projects[spring.io/projects] 你会看到一个Spring项目的列表,它们都是独立管理的，各自管理自己的发布周期和issue等。




[[overview-philosophy]]
== 设计哲学

当你学习一个框架时不仅仅要学习它是用来做什么的，而且要学习它所遵循的设计原则，下面这些就是Spring的设计原则。

* Spring在各个层次提供多种多样的选择，您可以在最后做出设计决策。
例如，你可以通过改变配置而改变持久化框架的选择，而不修改其他的任何东西，你的代码以及包括很多第三方的基础设施和集成的API。
* 兼容并包。Spring 灵活小巧不强制要求开发者去实现固定的东西，它广泛的支持各种不同的应用和设计。
* 为了维持强大的向后兼容性，Spring精心设计减少破坏性更新，支持精心选择的JDK版本，和第三方库，这使维护依赖Spring的项目变得简单。 
* 开发组精心设计API，这些直观的API将会被在很多版本中多年延续使用。
* 为了维持代码的质量，Spring强调，有意义，最新且准确的javadoc，它使目前仅有的几个可以宣称代码结构洁净，没有包循环依赖的项目。




[[overview-feedback]]
== 反馈和做出贡献

对于如何去用，诊断，调试问题，我们推荐您去Stackoverflow站去提问,
我们也有一个 https://spring.io/questions[提问页面] 提供了很多有用的建议信息
如果你有什么无法解决的问题或者新的功能建议请到 https://jira.spring.io/browse/spr[JIRA ]提交

如果你有解决方案或者建议性的修改请提交request pull到
https://github.com/spring-projects/spring-framework[Github]。
提醒一下，除了最琐碎的问题，我们希望每个问题都可以提交一个issue tracker这样可以方便以后进行参考。

获取更多信息请参考
https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md[CONTRIBUTING],
在主项目的页面.




[[overview-getting-started]]
== 入门

如果你刚刚开始入门Spring 你可能想通过新建一个 http://projects.spring.io/spring-boot/[Spring Boot]的应用来开始. Spring提供了一个快速（自以为是）的方法来建立一个开箱可用的应用，它创建在约定优于配置这一个Spring设计原则上, 这种设计可以让你更容易快速的开始。

你可以使用 http://start.spring.io/[start.spring.io]来生成一个极简的项目 或者根据 https://spring.io/guides["Getting Started" guides], 或者
https://spring.io/guides/gs/rest-service/[Getting Started Building a RESTful Web Service].
来新建项目。为了便于理解，这些入门资料，是基于任务的，大部分是以Spring boot作为基础的。它还涵盖了一些Spring 组合中的其他项目，如果你需要解决一些特定问题，你可能需要用到它们。
